import Link from "next/link";

export const metadata = { title: "Terms & Conditions — Finance Reports | DriveU" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-primary-900 text-white py-12 px-4">
        <div className="max-w-4xl mx-auto">
          <p className="text-blue-300 text-sm mb-2">DriveU Mobility Solutions Pvt. Ltd.</p>
          <h1 className="text-3xl font-bold">Terms &amp; Conditions</h1>
          <p className="text-blue-200 mt-2 text-sm">Finance Reports Internal Portal — Effective: January 1, 2025</p>
        </div>
      </div>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-8">

        <Section title="1. Acceptance of Terms">
          <p>By accessing and using the DriveU Finance Reports Portal ("Portal"), you agree to be bound by these Terms &amp; Conditions. This Portal is strictly for internal use by authorized employees of DriveU Mobility Solutions Private Limited, No. 19, 3rd Floor, 1st Cross Road, KHB Colony, 5th Block Koramangala, Bengaluru – 560095.</p>
          <p className="mt-3">If you do not agree to these terms, you must not access or use the Portal. Continued use of the Portal constitutes acceptance of any updates to these terms.</p>
        </Section>

        <Section title="2. Authorized Use">
          <p>Access to this Portal is granted exclusively to designated finance team members and authorized personnel of DriveU. You are permitted to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Download finance reports (B2C Revenue, B2B Revenue, Driver Wallet, Customer Wallet) for internal business analysis.</li>
            <li>View download history for audit and tracking purposes.</li>
            <li>Update your account password via the Change Password feature.</li>
          </ul>
          <p className="mt-3">You are strictly prohibited from:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Sharing your login credentials with any third party.</li>
            <li>Distributing downloaded reports outside the organization without proper authorization.</li>
            <li>Using the Portal for any purpose other than legitimate business operations.</li>
            <li>Attempting to bypass, circumvent, or tamper with any security measures.</li>
            <li>Scraping, reverse-engineering, or automated access of Portal data.</li>
          </ul>
        </Section>

        <Section title="3. Data Confidentiality">
          <p>All reports generated through this Portal contain sensitive financial and operational data of DriveU Mobility Solutions Pvt. Ltd. and its customers, drivers, and partners. You agree to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Treat all downloaded data as strictly confidential.</li>
            <li>Store downloaded files securely and delete them when no longer needed.</li>
            <li>Not share, publish, or disclose report data to unauthorized individuals, including third parties, media, or external agencies.</li>
            <li>Comply with all applicable data protection laws, including the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023.</li>
          </ul>
        </Section>

        <Section title="4. Account Responsibility">
          <p>You are fully responsible for all activity that occurs under your account. You must:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Maintain the confidentiality of your password at all times.</li>
            <li>Immediately notify the IT or Finance team if you suspect unauthorized access to your account.</li>
            <li>Log out of the Portal after each session, especially on shared devices.</li>
          </ul>
          <p className="mt-3">DriveU reserves the right to suspend or terminate access without notice if misuse is detected.</p>
        </Section>

        <Section title="5. Download Logging &amp; Audit">
          <p>All report download activities are logged in our internal database, including the report type, date range selected, timestamp of download, and the account that performed the download. These logs may be reviewed by the Finance, Compliance, or IT teams for audit purposes.</p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>All content, data, queries, and reports generated by this Portal are the exclusive intellectual property of DriveU Mobility Solutions Private Limited. No rights are transferred to users beyond the limited right to use data for internal business purposes as described in these Terms.</p>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          <p>This Portal is provided "as is" for internal operational use. DriveU makes no warranties, express or implied, regarding the accuracy, completeness, or fitness of the data for any particular purpose. Report data reflects the state of the underlying databases at the time of query execution.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>DriveU shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use this Portal, including but not limited to data loss, system downtime, or report inaccuracies.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>DriveU reserves the right to modify these Terms at any time. Continued use of the Portal after changes constitutes acceptance of the revised terms. Users will be notified of material changes by the Finance or IT team.</p>
        </Section>

        <Section title="11. Contact">
          <p>For questions regarding these Terms, please contact:</p>
          <div className="mt-2 bg-gray-50 rounded-lg px-4 py-3 text-sm">
            <p className="font-semibold text-gray-900">DriveU Mobility Solutions Private Limited</p>
            <p className="text-gray-600">No. 19, 3rd Floor, 1st Cross Road, KHB Colony</p>
            <p className="text-gray-600">5th Block Koramangala, Bengaluru – 560095</p>
            <p className="text-gray-600 mt-1">Website: <a href="https://www.driveu.in" className="text-primary-600 hover:underline" target="_blank" rel="noopener noreferrer">www.driveu.in</a></p>
          </div>
        </Section>

        <Footer />
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="bg-white rounded-2xl border border-gray-200 shadow-sm px-8 py-6">
      <h2 className="text-lg font-bold text-gray-900 mb-3">{title}</h2>
      <div className="text-sm text-gray-600 leading-relaxed">{children}</div>
    </section>
  );
}

function Footer() {
  return (
    <div className="flex flex-wrap gap-4 justify-center text-xs text-gray-400 pb-8 pt-4">
      <Link href="/terms" className="hover:text-primary-600">Terms &amp; Conditions</Link>
      <span>·</span>
      <Link href="/privacy-policy" className="hover:text-primary-600">Privacy Policy</Link>
      <span>·</span>
      <Link href="/cookies" className="hover:text-primary-600">Cookie Policy</Link>
      <span>·</span>
      <Link href="/copyright" className="hover:text-primary-600">Copyright</Link>
      <span>·</span>
      <Link href="/dashboard" className="hover:text-primary-600">Back to Dashboard</Link>
    </div>
  );
}
